config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  resources :events
  resources :event_attendees
  devise_for :users
  get 'users/:id', to: 'users#show', as: :user
  post '/events/:id', to: 'event_attendees#create', as: 'create_attending_event'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :event_attendees, dependent: :destroy
  has_many :attendees, through: :event_attendees, source: :user

  scope :past, -> { where('date < ?', Time.current) }
  scope :upcoming, -> { where('date > ?', Time.current) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  has_many :events
  has_many :event_attendees, dependent: :destroy
  has_many :attended_events, through: :event_attendees, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def new
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.find(params[:id])
    @event.attendees << current_user
    redirect_back fallback_location: root_path, notice: "You have succesfully registered for the event."
  end

  def destroy
    @attendance = User.find_by(id: current_user.id).event_attendees.find_by(event_id: params[:id])
    @attendance.destroy

    redirect_back fallback_location: root_path, status: :see_other, notice: "Event attendance deleted succesfully"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :owner_only, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to events_path, notice: "Event created succesfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: "Event updated succesfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other, notice: "Event deleted succesfully"
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :user_id)
  end

  def owner_only
    if current_user != Event.find(params[:id]).creator
      redirect_to root_url, alert: 'You are not allowed to do that'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_form.html.erb
<%= form_with model: event do |f| %>
  <ul>
    <% event.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>

  <%= f.label :title, 'Title' %>
  <%= f.text_field :title %></br></br>
  <%= f.label :description, 'Description' %>
  <%= f.text_area :description %></br></br>
  <%= f.label :date, 'Date' %>
  <%= f.date_field :date %></br></br>
  <%= f.label :location, 'Location' %>
  <%= f.text_field :location %></br></br>
  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Update event</h1>
<%= link_to "Home", root_path %>
<%= button_to "Logout", destroy_user_session_path, method: :delete  %>

<%= render 'event_form', event: @event %>

app/views/events/index.html.erb
<h1>Current events</h1>
<% if user_signed_in? %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete %>
  <%= link_to "Create new Event", new_event_path %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %>
<% if user_signed_in? %>
  <h2>Greetings, <%= current_user.username %></h2>
<% else %>
  <h2>Not logged in</h2>
<% end %>

<div>
  <h3>Upcoming events</h3>
  <% @events.upcoming.each do |e| %>
    <ul>
      <li>
        <h5><%= link_to e.title, e %></h5>
        <p>Date: <%= e.date %></p>
        <p><%= e.description %></p>
        <p>Location: <%= e.location %></p>
        <p>By: <%= link_to e.creator.email, e.creator %></p>
      </li>
    </ul>
  <% end %>
</div>

<div>
  <h3>Past events</h3>
  <% @events.past.each do |e| %>
    <ul>
      <li>
        <h5><%= link_to e.title, e %></h5>
        <p>Date: <%= e.date %></p>
        <p><%= e.description %></p>
        <p>Location: <%= e.location %></p>
        <p>By: <%= link_to e.creator.email, e.creator %></p>
      </li>
    </ul>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create event</h1>
<%= link_to "Home", root_path %>
<%= button_to "Logout", destroy_user_session_path, method: :delete  %>

<%= render 'event_form', event: @event %>

app/views/events/show.html.erb
<%= link_to "Home", root_path %>
<h1><%= @event.title %></h1>
<p>Date: <%= @event.date %></p>
<p><%= @event.description %></p>
<p>Location: <%= @event.location %></p>
<p>By: <%= User.find_by(id: @event.user_id).username %></p>
<% if current_user != @event.creator && !@event.attendees.include?(current_user) %>
  <%= link_to "Attend", create_attending_event_path(user_id: current_user.id, event_id: @event.id), data: {'turbo-method': :post} %>
<% else %>
  <p>You have registered for this event</p>
  <%= link_to 'Cancel attendance', event_attendee_path(user_id: current_user.id, event_id: @event.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<% end %>
<% if current_user == @event.creator %>
  <%= link_to 'Edit', edit_event_path(@event) %>
  <%= link_to 'Delete', event_path(@event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<% end %>
<div>
  <h5>People who is attending:</h5>
  <ul>
    <% @event.attendees.each do |a| %>
      <li><%= a.username %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if flash[:alert] %>
    <div class = "alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class = "alert alert-primary">
      <%= flash[:notice] %>
    </div>
  <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %> Posts</h1>

<% @user.events.each do |event| %>
  <ul>
    <li>
      <h5><%= event.title %></h5>
      <p>Date: <%= event.date %></p>
      <p><%= event.description %></p>
      <p>Location: <%= event.location %></p>
    </li>
  </ul>
<% end %>
<div>
  <h5>This user is attending to the following events:</h5>
  <ul>
    <% @user.attended_events.where('date > ?', Time.current).each do |a| %>
      <li><%= link_to a.title, a %></li>
    <% end %>
  </ul>
</div>
<div>
  <h5>This user has attended to the following events:</h5>
  <ul>
    <% @user.attended_events.where('date < ?', Time.current).each do |a| %>
      <li><%= link_to a.title, a %></li>
    <% end %>
  </ul>
</div>